### ISSUE TITLE
Feature Request: Secondary click to cross out squares

### ISSUE THREAD

**Issue by TiZ-HugLife** [adil192/super_nonogram#2]
Hi there!

I see that the latest version in Flathub lets you cross out squares. I'm glad this exists now! It's crucial to be able to keep track of deductions and reason about what is where. But you have to select it as a separate mode on the bottom to do that. That's pretty unwieldy. The equivalent game in Simon Tatham's puzzle collection, Pattern, lets you mark a square as ineligible with a secondary click. On the unofficial Android port, it's a tap-hold.

Would you be willing to implement this functionality in this app? Thanks kindly for your time! 🙂

# Tasks

- [x] Right click on desktop
- [x] Tap-hold on mobile

**Comment by adil192** [comment]
This would definitely improve the UX so thank you. I'm currently working on adding achievements to the game so I'll get on this afterward

**Comment by TiZ-HugLife** [comment]
Thank you very much! 😊
