### ISSUE TITLE
Not all numbers in the column descriptions are visible

### ISSUE THREAD

**Issue by ioutora** [adil192/super_nonogram#3]
First of all: thank you for providing Linux and Flatpak suuport. Also, I apologize if I make any mistakes in this issue as it's the first time I open one.

I noticed that column numbers get cut off in the middle of the fourth number, as can be seen here, in the first two columns:
![1](https://github.com/adil192/super_nonogram/assets/136457609/a902ee48-fcd0-4e1f-9062-01a3e42ed787)

It's not much of a problem when there are only 4 numbers, but with > 4 it's impossible to see the 5th and beyond like below:
![2](https://github.com/adil192/super_nonogram/assets/136457609/74c5015d-f017-4788-85e2-f78770d56240)

Here, the only unfinished column should be "2 1 1 2 1", buy only "2 1 1 2" is visible.
A similar problem can be seen below:
![3](https://github.com/adil192/super_nonogram/assets/136457609/1c374158-073b-453d-80cf-c530a39478fd)

Here, the only unfinished column is "1 3 2 2 1", but the last "1" doesn't appear in the column description.

Tested on: Flatpak, AppImage and Web(Firefox) versions on Arch Linux with Gnome desktop, 1920x1080 and 4k monitors.

**Comment by putradnata** [comment]
Ahh, so this is the reason why I cannot beat Level 37 😢
I just want to ask the dev about this, and @ioutora represent me 😢  

btw, thank you dev for awesome works! @adil192  :)
